package io.github.capure.voltcore.exception;

public class UsernameAlreadyInUseException extends Exception {
}
